import type { Spending } from './schemas'

export const mockMonthlyBudget = 185_000

export const initialMockSpendings: Spending[] = [
  {
    id: 'sp-001',
    sum: 4320,
    date: '2026-04-26',
    bank_category: 'Restaurants',
    bank_description: 'Duo Gastrobar',
    currency: 'RUB',
    category_name: 'Еда вне дома',
    comment: 'Ужин после защиты проекта',
  },
  {
    id: 'sp-002',
    sum: 1890,
    date: '2026-04-25',
    bank_category: 'Groceries',
    bank_description: 'ВкусВилл',
    currency: 'RUB',
    category_name: 'Продукты',
    comment: 'Закупка на неделю',
  },
  {
    id: 'sp-003',
    sum: 3490,
    date: '2026-04-24',
    bank_category: 'Software',
    bank_description: 'JetBrains',
    currency: 'RUB',
    category_name: 'Подписки',
    comment: 'Инструменты разработки',
  },
  {
    id: 'sp-004',
    sum: 860,
    date: '2026-04-24',
    bank_category: 'Transport',
    bank_description: 'Yandex Go',
    currency: 'RUB',
    category_name: 'Транспорт',
    comment: 'Такси до кампуса',
  },
  {
    id: 'sp-005',
    sum: 12490,
    date: '2026-04-22',
    bank_category: 'Electronics',
    bank_description: 'DNS',
    currency: 'RUB',
    category_name: 'Техника',
    comment: 'SSD для ноутбука',
  },
  {
    id: 'sp-006',
    sum: 5200,
    date: '2026-04-21',
    bank_category: 'Education',
    bank_description: 'Stepik',
    currency: 'RUB',
    category_name: 'Образование',
    comment: 'Курс по ML',
  },
  {
    id: 'sp-007',
    sum: 2490,
    date: '2026-04-19',
    bank_category: 'Health',
    bank_description: 'Аптека 36.6',
    currency: 'RUB',
    category_name: 'Здоровье',
    comment: 'Витамины',
  },
  {
    id: 'sp-008',
    sum: 780,
    date: '2026-04-18',
    bank_category: 'Coffee',
    bank_description: 'Surf Coffee',
    currency: 'RUB',
    category_name: 'Кофе',
    comment: 'Рабочая встреча',
  },
  {
    id: 'sp-009',
    sum: 6200,
    date: '2026-04-16',
    bank_category: 'Clothes',
    bank_description: 'Uniqlo',
    currency: 'RUB',
    category_name: 'Одежда',
    comment: 'Базовые вещи',
  },
  {
    id: 'sp-010',
    sum: 1490,
    date: '2026-04-15',
    bank_category: 'Entertainment',
    bank_description: 'Кино',
    currency: 'RUB',
    category_name: 'Развлечения',
    comment: 'Билеты',
  },
  {
    id: 'sp-011',
    sum: 3100,
    date: '2026-04-13',
    bank_category: 'Groceries',
    bank_description: 'Перекресток',
    currency: 'RUB',
    category_name: 'Продукты',
    comment: 'Еда домой',
  },
  {
    id: 'sp-012',
    sum: 1290,
    date: '2026-04-11',
    bank_category: 'Subscriptions',
    bank_description: 'Spotify',
    currency: 'RUB',
    category_name: 'Подписки',
    comment: 'Музыка',
  },
  {
    id: 'sp-013',
    sum: 920,
    date: '2026-04-09',
    bank_category: 'Transport',
    bank_description: 'Метро',
    currency: 'RUB',
    category_name: 'Транспорт',
    comment: 'Пополнение карты',
  },
  {
    id: 'sp-014',
    sum: 8100,
    date: '2026-04-07',
    bank_category: 'Home',
    bank_description: 'Ozon',
    currency: 'RUB',
    category_name: 'Дом',
    comment: 'Организация рабочего места',
  },
  {
    id: 'sp-015',
    sum: 4550,
    date: '2026-04-05',
    bank_category: 'Restaurants',
    bank_description: 'Кофемания',
    currency: 'RUB',
    category_name: 'Еда вне дома',
    comment: 'Встреча с командой',
  },
]

export const initialMockForecast: Spending[] = [
  {
    id: 'fc-001',
    sum: 18_500,
    date: '2026-05-02',
    bank_category: 'Rent',
    bank_description: 'Аренда',
    currency: 'RUB',
    category_name: 'Жилье',
    comment: 'Регулярный платеж',
  },
  {
    id: 'fc-002',
    sum: 15_800,
    date: '2026-05-05',
    bank_category: 'Groceries',
    bank_description: 'Продукты',
    currency: 'RUB',
    category_name: 'Продукты',
    comment: 'Ожидаемый месячный расход',
  },
  {
    id: 'fc-003',
    sum: 8800,
    date: '2026-05-08',
    bank_category: 'Education',
    bank_description: 'Обучение',
    currency: 'RUB',
    category_name: 'Образование',
    comment: 'Вероятная покупка курса',
  },
  {
    id: 'fc-004',
    sum: 6900,
    date: '2026-05-12',
    bank_category: 'Transport',
    bank_description: 'Транспорт',
    currency: 'RUB',
    category_name: 'Транспорт',
    comment: 'Такси и общественный транспорт',
  },
  {
    id: 'fc-005',
    sum: 7400,
    date: '2026-05-16',
    bank_category: 'Restaurants',
    bank_description: 'Кафе и рестораны',
    currency: 'RUB',
    category_name: 'Еда вне дома',
    comment: 'Риск роста на выходных',
  },
  {
    id: 'fc-006',
    sum: 5200,
    date: '2026-05-20',
    bank_category: 'Subscriptions',
    bank_description: 'Подписки',
    currency: 'RUB',
    category_name: 'Подписки',
    comment: 'Повторяющиеся сервисы',
  },
]

export const importedMockSpendings: Spending[] = [
  {
    id: 'imp-001',
    sum: 1320,
    date: '2026-04-27',
    bank_category: 'Coffee',
    bank_description: 'Cofix',
    currency: 'RUB',
    category_name: 'Кофе',
    comment: 'Добавлено из CSV',
  },
  {
    id: 'imp-002',
    sum: 2760,
    date: '2026-04-27',
    bank_category: 'Groceries',
    bank_description: 'Азбука вкуса',
    currency: 'RUB',
    category_name: 'Продукты',
    comment: 'Добавлено из CSV',
  },
]
